version: '3.8'
services:
    wordpress:
        image: wordpress-multisite
        restart: unless-stopped
        container_name: wordpress
        build:
            dockerfile: Dockerfile # this line is actually redundant here - you need it only if you want to use some custom name for your Dockerfile
            context: ./
        environment:
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_HOST: wordpress-db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./app:/var/www/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.wordpress.rule=Host(`wp.docker.localhost`)"
            # http with redirection
            - "traefik.http.routers.wordpress.tls=true"
            - "traefik.http.routers.wordpress.entrypoints=https"
            - "traefik.http.services.wordpress.loadbalancer.server.port=80"
            - "traefik.docker.network=web"

        networks:
            - web
            - internal
    wordpress-db:
        image: mariadb:10.6-focal
        container_name: wordpress-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - web
            - internal
    wp-redis:
        image: redis:7.0-alpine
        container_name: wp-redis
        restart: always
        networks:
            - web
            - internal
        ports:
            - "6380:6379"
networks:
    web:
        external: true
    internal:
        external: false
